server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://39.106.160.119:3306/book_shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: book_remote
    password: ZBw046vGX7D0eB3o
    driver-class-name: com.mysql.cj.jdbc.Driver

