server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: book_local
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

