server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxx?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: xxx
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver

